# -*- coding: utf-8 -*-
# :Project:   pymeshfix -- Configuration to build and upload Linux wheels to PyPI
# :Author:    Alex Kaszynski <akascap@gmail.com>
# :License:   MIT License

# borrowed parts from
# https://github.com/python-rapidjson/python-rapidjson/blob/master/.appveyor.yml

# Builds wheels for Linux using cibuildwheel, inside the manylinux1 Docker image.
# builds 64-bit Python3.5, Python3.6, Python3.7

dist: xenial

matrix:
  include:
    - sudo: required
      language: python
      python: "3.7"
      services:
        - docker
      env: PIP=pip
    - os: osx
      osx_image: xcode8.3

env:
  global:
    - CIBW_BEFORE_BUILD_LINUX="pip install numpy==1.15.0; pip install cython; yum install libXt -y"
    - CIBW_TEST_REQUIRES="pytest"
    - CIBW_TEST_COMMAND="pytest {project}/tests/"
    - CIBW_SKIP="cp27-* cp34-* cp38-* *manylinux1_i686*"
    - TWINE_USERNAME=akaszynski
      # Note: TWINE_PASSWORD is set in Travis settings
    # Doctr deploy key for pyvista/pymeshfix
    - secure: "WaVtsHs+O5e4Sbxo3SP0J/M8ERsh+07eFnaBbC0WfN30gBz13l5SGH1GRPUhW0kw2+Nzk2ZXJsGbVe0vLJt1X7dTHkpF0eHUfDIQzNqB0/8MYY7fT8yV4zL6YLIGgj/PcY4QAzCkBJJmX7lFqs5vihRoycGQ/lZ0gqpSoPwtYDBQFUqpD5rQg886KJJLXKzKV6X+Or5d1kxIzwQCmGMIZMslQOTbnv35xh9uj1y6qGATTZlaOoBWCHOmQYqcda4axD/sQKGSyS55z9G+e7A91AdCUKP/Ql4ejsZb1+DxucogFMIxU3hD1zQnLBhiP959QFGjoAJ1igeJx4V9t7gx7j3FevkzSg10ULjUfM1LBIivKq2tsboirtJG7nu9xDUlxHLDMivdeAMPI3w2TDqmPHryz1QwZEn6FYCdJkoKdWR0IyOXsIhozft7GHiumG+gYiBvBN877PVp0Meu9OXBpk8BtmXuL8P06LCNIVVaqYtYdMrJapBewhdbS7YmUckNGor5C5VrCz/5uUKoCUtFKCo+JTjdEZcyfpeeHs5wo5U2Fh2W/ivoBgCf8i3yBWerz7dx7KfmEck9Cy0unk15AaMGEhkBFGgThsxE1k8zu1Ggf5j9o4ta9RhRn9ajl/j3Pz78TmWM5JE0ZGSYiybU0g6MrXhuXamOtssYwixKfoo="


before_install:
  # configure a headless display
  - git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
  - source ./gl-ci-helpers/travis/setup_headless_display.sh


install:
  - pip3 install --upgrade cibuildwheel

script:
  - cibuildwheel --output-dir wheelhouse
  - ls ./wheelhouse
  # Make documentation
  - if [ "${TRAVIS_TAG:-}" != "" ]; then
      python3 setup.py sdist;
      cp dist/*.tar.gz wheelhouse/;
      pip3 install twine;
      python3 -m twine upload --skip-existing wheelhouse/*;
    fi

notifications:
  email: false
